services:
  qcms-caliper-be:
    container_name: qcms-caliper-be
    build: .
    image: qcms-caliper-be
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    ports:
      - '${PORT:-8085}:${PORT:-8085}'
    networks:
      - app-network
    volumes:
      - ./wwebjs_auth:/app/.wwebjs_auth
      - ./wwebjs_cache:/app/.wwebjs_cache

networks:
  app-network:
    driver: bridge
