version: '3.9'

services:
  qcms-caliper-be:
    container_name: qcms-caliper-be
    build: .
    image: qcms-caliper-be
    env_file:
      - .env
    ports:
      - '${PORT:-8085}:${PORT:-8085}'
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: qcms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qcms_caliper
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-prootpass',
        ]
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
