services:
  qcms-caliper-be-staging:
    container_name: qcms-caliper-be-staging
    build: .
    image: qcms-caliper-be-staging
    env_file:
      - .env.staging
    environment:
      - TZ=Asia/Jakarta
    ports:
      - '8086:8085'
    networks:
      - app-network-staging
    volumes:
      # volume untuk Baileys staging
      - ./baileys_auth_info_staging:/app/baileys_auth_info

networks:
  app-network-staging:
    driver: bridge
